/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsFeed.view.MyPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.mypanel',

    requires: [
        'NewsFeed.view.MyPanelViewModel',
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    viewModel: {
        type: 'mypanel'
    },
    height: 250,
    width: 400,
    title: 'Notifications',

    items: [
        {
            xtype: 'dataview',
            height: '100%',
            itemSelector: 'div',
            itemTpl: [
                'Data View Item {string}'
            ]
        }
    ]

});