/*
 * File: app/view/MyPanel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsFeed.view.MyPanel', {
    extend: 'Ext.panel.Panel',

    requires: [
        'Ext.view.View',
        'Ext.XTemplate'
    ],

    height: '100%',
    width: 400,
    title: 'Notification',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'dataview',
                    height: '100%',
                    itemSelector: 'div',
                    itemTpl: [
                        '',
                        '<img class="{icon-message}" style="width:50px; height: 50px; float: left;margin-bottom: 10px;"/>',
                        '<p style=\"font-size:10pt\"><b> {user}</b>',
                        '    &nbsp;&nbsp;&nbsp;&nbsp;{type}',
                        '    &nbsp;&nbsp;&nbsp;&nbsp;<strong>{title}</strong></p>',
                        '<p style=\"font-size:10pt\">{notify}</p>',
                        '<hr>'
                    ],
                    store: 'notify'
                }
            ]
        });

        me.callParent(arguments);
    }

});