/*
 * File: app/view/MyToolbar.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsFeed.view.MyToolbar', {
    extend: 'Ext.toolbar.Toolbar',

    requires: [
        'Ext.button.Button'
    ],

    height: 40,
    width: '100%',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    activeFn: function(region) {
                        Ext.create('Ext.Panel', {
                            centered : true,
                            html     : 'Hello'
                        }).show();

                        /*/Ext.create('NewsFeed.view.MyPanel').show();

                        mypanel=Ext.create('Ext.Panel', {
                            html: 'Floating Panel',
                            hideOnMaskTap:true,
                            modal:true,
                            floating:true,
                            centered:true,
                            padding: 10
                        });

                        Ext.Viewport.add(mypanel);

                        mypanel.show();

                        /*
                        var anchorX = region.left + (region.right - region.left) / 2,
                        anchorY = region.bottom + 1;




                        var notifyWin = Ext.create('Ext.Window', {
                        title: false,
                        frame: false,
                        frameHeader: false,
                        header: false,
                        autoShow: false,
                        resizable: false,
                        plain: true,
                        width: 200,
                        x: region.right - 200,
                        y: anchorY,
                        items: Ext.create('NewsFeed.view.MyPanel'),
                        listeners: {
                        afterrender: function (scope, eOpts) { notifyWin.show(); }
                        }
                        });
                        */
                    },
                    height: 31,
                    itemId: 'mybutton',
                    width: 30,
                    destroyMenu: true,
                    iconCls: 'icon-notify',
                    text: ' '
                }
            ]
        });

        me.callParent(arguments);
    }

});