/*
 * File: app/view/MyToolbar.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsFeed.view.MyToolbar', {
    extend: 'Ext.toolbar.Toolbar',
    alias: 'widget.mytoolbar',

    requires: [
        'NewsFeed.view.MyToolbarViewModel',
        'Ext.button.Button'
    ],

    viewModel: {
        type: 'mytoolbar'
    },
    height: 45,
    width: '100%',

    items: [
        {
            xtype: 'button',
            activeFn: function(region) {
                var anchorX = region.left + (region.right - region.left) / 2,
                    anchorY = region.bottom + 1;




                var notifyWin = Ext.create('Ext.Window', {
                    title: false,
                    frame: false,
                    frameHeader: false,
                    header: false,
                    autoShow: false,
                    resizable: false,
                    plain: true,
                    width: 200,
                    x: region.right - 200,
                    y: anchorY,
                    items: Ext.create('NewsFeed.view.MyPanel'),
                    listeners: {
                        afterrender: function (scope, eOpts) { notifyWin.show(); }
                    }
                });


                if (notifyWin.isVisible() ){
                    notifyWin.hide();
                } else {
                    notifyWin.show();
                    notifyWin.setPosition( region.right - notifyWin.getWidth(), anchorY, false);
                }
            },
            itemId: 'mybutton',
            width: 33,
            iconCls: 'icon-notify'
        }
    ]

});