/*
 * File: app/model/notify.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('NewsFeed.model.notify', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'image',
            type: 'string'
        },
        {
            name: 'type',
            type: 'string'
        },
        {
            name: 'title',
            type: 'string'
        },
        {
            name: 'datetime',
            type: 'date'
        },
        {
            name: 'url',
            type: 'string'
        },
        {
            name: 'user',
            type: 'string'
        },
        {
            name: 'notify',
            type: 'string'
        }
    ]
});